create_clock -period 8.000 -name clk [get_ports clk]
set_false_path -from [get_ports rst_n] -to clk
set_input_delay -clock clk -max 2.000 [get_ports start]
set_input_delay -clock clk -min 1.000 [get_ports start]
set_output_delay -clock clk -max 2.000 [get_ports num]
set_output_delay -clock clk -min 1.000 [get_ports num]


set_property PACKAGE_PIN L16 [get_ports clk]
set_property PACKAGE_PIN T16 [get_ports rst_n]
set_property PACKAGE_PIN W13 [get_ports start]
set_property PACKAGE_PIN D18 [get_ports {num[3]}]
set_property PACKAGE_PIN G14 [get_ports {num[2]}]
set_property PACKAGE_PIN M15 [get_ports {num[1]}]
set_property PACKAGE_PIN M14 [get_ports {num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports start]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 1 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {lenet_u/u_conv1/start_r_reg[0]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 4 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {num_OBUF[0]} {num_OBUF[1]} {num_OBUF[2]} {num_OBUF[3]}]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
